export {
  EDGE_MARGIN,
  REGIONS,
  REGION_ORDER,
  fitsOnLand,
  isOnLand,
  neighbours,
  randomGroundPositionIn,
  regionAt,
  regionById,
  WORLD_BOUNDS,
  WORLD_SHADOW_EXTENT,
  type Region,
  type RegionId,
} from './regions.logic';
